import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export interface EmailData {
  to: string | string[]
  subject: string
  html: string
  from?: string
  replyTo?: string
}

export async function sendEmail({ to, subject, html, from, replyTo }: EmailData) {
  try {
    const { data, error } = await resend.emails.send({
      from: from || 'Freedom Suite <noreply@scalewithruth.com>',
      to: Array.isArray(to) ? to : [to],
      subject,
      html,
      replyTo: replyTo || 'support@scalewithruth.com'
    })

    if (error) {
      console.error('Email send error:', error)
      return { success: false, error: error.message }
    }

    console.log('Email sent successfully:', data?.id)
    return { success: true, id: data?.id }
  } catch (error) {
    console.error('Email service error:', error)
    return { 
      success: false, 
      error: error instanceof Error ? error.message : 'Unknown error' 
    }
  }
}

// Email Templates for the 8-System Suite
export const EmailTemplates = {
  // Executive Intelligence Briefings
  executiveBriefing: (data: any) => `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 12px 12px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">🧠 Daily Executive Briefing</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0;">${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>
      
      <div style="background: white; padding: 30px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="margin-bottom: 24px;">
          <h2 style="color: #1f2937; font-size: 18px; margin: 0 0 8px 0;">🎯 Top Priority</h2>
          <p style="color: #4b5563; margin: 0;">${data.topPriority}</p>
        </div>
        
        <div style="margin-bottom: 24px;">
          <h2 style="color: #1f2937; font-size: 18px; margin: 0 0 8px 0;">🏆 Key Win</h2>
          <p style="color: #10b981; margin: 0; font-weight: 500;">${data.keyWin}</p>
        </div>
        
        <div style="margin-bottom: 24px;">
          <h2 style="color: #1f2937; font-size: 18px; margin: 0 0 8px 0;">⚠️ Main Concern</h2>
          <p style="color: #ef4444; margin: 0;">${data.mainConcern}</p>
        </div>
        
        <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 24px;">
          <h3 style="color: #1f2937; font-size: 16px; margin: 0 0 12px 0;">📊 Business Health Score</h3>
          <div style="display: flex; align-items: center; gap: 12px;">
            <div style="font-size: 24px; font-weight: bold; color: ${data.healthScore >= 8 ? '#10b981' : data.healthScore >= 6 ? '#f59e0b' : '#ef4444'}">${data.healthScore}/10</div>
            <div style="color: #6b7280;">${data.healthTrend === 'improving' ? '↗️ Improving' : data.healthTrend === 'declining' ? '↘️ Declining' : '→ Stable'}</div>
          </div>
        </div>
        
        <div style="margin-bottom: 24px;">
          <h3 style="color: #1f2937; font-size: 16px; margin: 0 0 12px 0;">⚡ Immediate Actions</h3>
          ${data.immediateActions?.map((action: string) => 
            `<div style="padding: 8px 0; border-left: 3px solid #3b82f6; padding-left: 12px; margin-bottom: 8px; color: #4b5563;">• ${action}</div>`
          ).join('') || '<p style="color: #6b7280; font-style: italic;">No immediate actions required.</p>'}
        </div>
        
        <div style="text-align: center; padding-top: 20px; border-top: 1px solid #e5e7eb;">
          <p style="color: #6b7280; font-size: 14px; margin: 0;">Generated by Freedom Suite AI Intelligence</p>
        </div>
      </div>
    </div>
  `,

  // Predictive Alerts
  criticalAlert: (data: any) => `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%); padding: 30px; border-radius: 12px 12px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">🚨 Critical Business Alert</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0;">Immediate attention required</p>
      </div>
      
      <div style="background: white; padding: 30px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
          <h2 style="color: #dc2626; font-size: 18px; margin: 0 0 8px 0;">${data.alertTitle}</h2>
          <p style="color: #7f1d1d; margin: 0; font-weight: 500;">${data.alertMessage}</p>
        </div>
        
        <div style="margin-bottom: 24px;">
          <h3 style="color: #1f2937; font-size: 16px; margin: 0 0 12px 0;">📋 Details</h3>
          <p style="color: #4b5563; line-height: 1.6; margin: 0;">${data.detailedExplanation}</p>
        </div>
        
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px;">
          <div style="background: #f9fafb; padding: 16px; border-radius: 8px;">
            <h4 style="color: #1f2937; font-size: 14px; margin: 0 0 4px 0;">⏰ Time to Impact</h4>
            <p style="color: #dc2626; font-weight: 600; margin: 0;">${data.timeToImpact}</p>
          </div>
          <div style="background: #f9fafb; padding: 16px; border-radius: 8px;">
            <h4 style="color: #1f2937; font-size: 14px; margin: 0 0 4px 0;">💰 Revenue at Risk</h4>
            <p style="color: #dc2626; font-weight: 600; margin: 0;">$${data.affectedRevenue?.toLocaleString()}</p>
          </div>
        </div>
        
        <div style="margin-bottom: 24px;">
          <h3 style="color: #1f2937; font-size: 16px; margin: 0 0 12px 0;">🎯 Recommended Actions</h3>
          ${data.recommendedActions?.map((action: string) => 
            `<div style="padding: 12px; background: #eff6ff; border-left: 4px solid #3b82f6; margin-bottom: 8px; border-radius: 0 4px 4px 0;">
              <p style="color: #1e40af; margin: 0; font-weight: 500;">${action}</p>
            </div>`
          ).join('') || '<p style="color: #6b7280;">No specific actions recommended.</p>'}
        </div>
        
        <div style="text-align: center; padding: 20px; background: #f3f4f6; border-radius: 8px;">
          <a href="https://ai.scalewithruth.com" style="display: inline-block; background: #3b82f6; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: 600;">
            View in Executive Intelligence →
          </a>
        </div>
      </div>
    </div>
  `,

  // Cash Flow Warnings
  cashFlowWarning: (data: any) => `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%); padding: 30px; border-radius: 12px 12px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">💰 Cash Flow Alert</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0;">Payment attention needed</p>
      </div>
      
      <div style="background: white; padding: 30px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="background: #fffbeb; border: 1px solid #fed7aa; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
          <h2 style="color: #d97706; font-size: 18px; margin: 0 0 8px 0;">⚠️ ${data.warningType}</h2>
          <p style="color: #92400e; margin: 0;">${data.message}</p>
        </div>
        
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px;">
          <div style="text-align: center; padding: 20px; background: #f9fafb; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #dc2626;">$${data.overdueAmount?.toLocaleString()}</div>
            <div style="color: #6b7280; font-size: 14px;">Overdue Amount</div>
          </div>
          <div style="text-align: center; padding: 20px; background: #f9fafb; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #059669;">$${data.projectedInflow?.toLocaleString()}</div>
            <div style="color: #6b7280; font-size: 14px;">Expected Next 30 Days</div>
          </div>
        </div>
        
        <div style="text-align: center;">
          <a href="https://suite.scalewithruth.com/cash-flow-command" style="display: inline-block; background: #3b82f6; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: 600;">
            Review Cash Flow →
          </a>
        </div>
      </div>
    </div>
  `,

  // Client Journey Updates  
  clientJourneyUpdate: (data: any) => `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%); padding: 30px; border-radius: 12px 12px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">🎯 Client Journey Update</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0;">${data.clientName}</p>
      </div>
      
      <div style="background: white; padding: 30px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="margin-bottom: 24px;">
          <h2 style="color: #1f2937; font-size: 18px; margin: 0 0 12px 0;">📈 Progress Update</h2>
          <div style="background: #f3f4f6; height: 8px; border-radius: 4px; margin-bottom: 8px;">
            <div style="background: #8b5cf6; height: 8px; border-radius: 4px; width: ${data.progressPercentage}%;"></div>
          </div>
          <p style="color: #6b7280; font-size: 14px; margin: 0;">${data.progressPercentage}% complete • Stage: ${data.currentStage}</p>
        </div>
        
        <div style="background: #f8fafc; padding: 16px; border-radius: 8px; margin-bottom: 24px;">
          <h3 style="color: #1f2937; font-size: 16px; margin: 0 0 8px 0;">✅ Completed This Week</h3>
          <p style="color: #10b981; margin: 0;">${data.completedAction}</p>
        </div>
        
        <div style="background: #fef7ff; padding: 16px; border-radius: 8px; border: 1px solid #e9d5ff;">
          <h3 style="color: #7c2d12; font-size: 16px; margin: 0 0 8px 0;">⏭️ Next Action</h3>
          <p style="color: #6b21a8; margin: 0; font-weight: 500;">${data.nextAction}</p>
          <p style="color: #9333ea; font-size: 14px; margin: 8px 0 0 0;">Due: ${data.nextActionDue}</p>
        </div>
      </div>
    </div>
  `
}

// Notification trigger functions
export async function sendExecutiveBriefing(userEmail: string, briefingData: any) {
  return await sendEmail({
    to: userEmail,
    subject: `🧠 Your Daily Executive Briefing - ${new Date().toLocaleDateString()}`,
    html: EmailTemplates.executiveBriefing(briefingData),
    from: 'Executive AI <ai@scalewithruth.com>'
  })
}

export async function sendCriticalAlert(userEmail: string, alertData: any) {
  return await sendEmail({
    to: userEmail,
    subject: `🚨 CRITICAL: ${alertData.alertTitle}`,
    html: EmailTemplates.criticalAlert(alertData),
    from: 'Freedom Suite Alerts <alerts@scalewithruth.com>'
  })
}

export async function sendCashFlowWarning(userEmail: string, warningData: any) {
  return await sendEmail({
    to: userEmail,
    subject: `💰 Cash Flow Alert: ${warningData.warningType}`,
    html: EmailTemplates.cashFlowWarning(warningData)
  })
}

export async function sendClientJourneyUpdate(userEmail: string, journeyData: any) {
  return await sendEmail({
    to: userEmail,  
    subject: `🎯 Client Update: ${journeyData.clientName}`,
    html: EmailTemplates.clientJourneyUpdate(journeyData)
  })
}